# Based on the Gruber Darker palette

background #181818
foreground #e4e4ef
selection_background #453d41
selection_foreground #e4e4ef
url_color #73c936
cursor #ffdd33
cursor_text_color background

# normal
color0 #181818
color1 #f43841
color2 #73c936
color3 #ffdd33
color4 #96a6c8
color5 #9e95c7
color6 #565f73
color7 #e4e4ef

# bright
color8 #453d41
color9 #ff4f58
color10 #73c936
color11 #ffdd33
color12 #96a6c8
color13 #9e95c7
color14 #565f73
color15 #f5f5f5