ubuntu fd fd-find
debian fd fd-find
ubuntu openssl  libssl-dev
debian openssl  libssl-dev
ubuntu pkgconf  pkg-config
debian pkgconf  pkg-config

wxwidgets ubuntu libwxgtk3.0-gtk3-dev
wxwidgets debian libwxgtk3.0-gtk3-dev
libffi ubuntu libffi-dev
libffi debian libffi-dev
unixodbc ubuntu unixodbc-dev
unixodbc debian unixodbc-dev


# Fonts
macos symbols-nerd-font   cask:font-symbols-only-nerd-font
macos jetbrains-mono      cask:font-jetbrains-mono
macos victor-mono         cask:font-victor-mono

arch symbols-nerd-font  ttf-nerd-fonts-symbols-mono
arch jetbrains-mono     ttf-jetbrains-mono
arch victor-mono        aur:ttf-victor-mono